### ISSUE TITLE
Add Windows Builds

### ISSUE THREAD

**Issue by dtip** [conda-forge/pango-feedstock#18]
Hello folks. Are there any plans to add Windows support?

**Comment by pkgw** [comment]
I think I may have looked into it at some point, but if you don't see a pull request here, there aren't any plans :-)

For reference, [here's their README.win32](https://github.com/GNOME/pango/blob/master/README.win32) document.

**Comment by dtip** [comment]
Perhaps we can leave this issue to sit here and see if it gathers any support.

I would imagine there are others out there who would prefer a quick `conda install pango` rather than having to work through that readme every time. Thanks though :)

**Comment by mdekstrand** [comment]
Getting Pango working on Windows is a prereq for Conda being a good way to install Weasyprint on Windows. Right now Windows Weasyprint installations are very tedious.

**Comment by dtip** [comment]
@mdekstrand please check https://github.com/conda-forge/magics-feedstock/blob/master/recipe/bld.bat for the workaround we ended up using. Feel free to reach out by email if you'd like help :)

**Comment by pkgw** [comment]
Done! Fixed by #28.
