### ISSUE TITLE
The pangoft2 library isn't being included in the windows package

### ISSUE THREAD

**Issue by NormanT7** [conda-forge/pango-feedstock#77]
Based on the the following line, it looks like the pangoft2 library should be included??

https://github.com/conda-forge/pango-feedstock/blob/4d280e5a41bf3d4d4f9a9e917c2c32fa67d0a761/recipe/meta.yaml#L64

However, when I install pango from conda-forge on Windows there aren't any pangoft2 libraries that actually get installed. I can see pango-1.0-0, pangocairo-1.0-0, and pangowin32-1.0-0 dlls but no pangoft2 anything.

**Comment by AlexRusuDatavid** [comment]
+1 same issue: 
OSError: cannot load library 'pangoft2-1.0-0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'pangoft2-1.0-0'

**Comment by DrShushen** [comment]
Same exact error here on Windows. Could this please be included?

**Comment by pkgw** [comment]
I believe this issue should be fixed now. Looking at the latest Windows package (`pango-1.54.0-hbb871f6_2`), it looks like the `PangoFT2` files are in all the places they should be.

**Comment by pkgw** [comment]
For unrelated reasons, we rebuilt the pango package yesterday and the new version continues to look good to me. I'm going to close this issue; please comment if the issue appears to be persisting with the latest package(s).
