### ISSUE TITLE
Incorrect / incomplete rebuild for harfbuzz 10

### ISSUE THREAD

**Issue by larsoner** [conda-forge/pango-feedstock#81]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

[This](https://github.com/conda-forge/pango-feedstock/pull/80) was green and merged but failed on `main`

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1104754&view=results

Something about `gio` not being available. Not sure if it's worth a restart or why it happened on `main` but not on that PR?

In any case it is making it so I can't upgrade some libraries because of this one's dependency on older `harfbuzz`.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by pkgw** [comment]
Yeah, it looks like there were some package updates in between the PR test build and the merged build that caused the latter to fail — we now need to explicitly list a few more dependencies to pull in some development-only files. This should be dealt with in #82.

**Comment by pkgw** [comment]
#82 is merged now; hopefully new packages should actually get built and make it through the system this time.

**Comment by pkgw** [comment]
Looks like this is indeed now fixed. The final build was all green and the bot has proposed harfbuzz 10 migrations for some packages that depend on pango.
